### ISSUE TITLE
Problem with Archiving project

### ISSUE THREAD

**Issue by filip-aetherius** [pointfreeco/swift-custom-dump#115]
**Describe the bug**
Give a clear and concise description of what the bug is.

Rename failed: /Users/test/Library/Developer/Xcode/DerivedData/Test-glvqxrieyduwirfnaoouzklnojya/Build/Intermediates.noindex/ArchiveIntermediates/test-staging/IntermediateBuildFilesPath/swift-custom-dump.build/Release-iphoneos/CustomDump.build/Objects-normal/arm64/Speech-bad90112.o.tmp -> /Users/test/Library/Developer/Xcode/DerivedData/test-glvqxrieyduwirfnaoouzklnojya/Build/Intermediates.noindex/ArchiveIntermediates/test-staging/IntermediateBuildFilesPath/swift-custom-dump.build/Release-iphoneos/CustomDump.build/Objects-normal/arm64/Speech.o: No such file or directory

Rename failed: /Users/test/Library/Developer/Xcode/DerivedData/Test-glvqxrieyduwirfnaoouzklnojya/Build/Intermediates.noindex/ArchiveIntermediates/test-staging/IntermediateBuildFilesPath/swift-custom-dump.build/Release-iphoneos/CustomDump.build/Objects-normal/arm64/CoreMotion-07ef2dfa.o.tmp -> /Users/test/Library/Developer/Xcode/DerivedData/test-glvqxrieyduwirfnaoouzklnojya/Build/Intermediates.noindex/ArchiveIntermediates/test-staging/IntermediateBuildFilesPath/swift-custom-dump.build/Release-iphoneos/CustomDump.build/Objects-normal/arm64/CoreMotion.o: No such file or directory

Rename failed: /Users/test/Library/Developer/Xcode/DerivedData/Test-glvqxrieyduwirfnaoouzklnojya/Build/Intermediates.noindex/ArchiveIntermediates/test-staging/IntermediateBuildFilesPath/swift-custom-dump.build/Release-iphoneos/CustomDump.build/Objects-normal/arm64/CoreLocation-aef9f0f0.o.tmp -> /Users/test/Library/Developer/Xcode/DerivedData/test-glvqxrieyduwirfnaoouzklnojya/Build/Intermediates.noindex/ArchiveIntermediates/test-staging/IntermediateBuildFilesPath/swift-custom-dump.build/Release-iphoneos/CustomDump.build/Objects-normal/arm64/CoreLocation.o: No such file or directory

Rename failed: /Users/test/Library/Developer/Xcode/DerivedData/test-glvqxrieyduwirfnaoouzklnojya/Build/Intermediates.noindex/ArchiveIntermediates/test-staging/IntermediateBuildFilesPath/swift-custom-dump.build/Release-iphoneos/CustomDump.build/Objects-normal/arm64/Swift-236a70eb.o.tmp -> /Users/test/Library/Developer/Xcode/DerivedData/test-glvqxrieyduwirfnaoouzklnojya/Build/Intermediates.noindex/ArchiveIntermediates/test-staging/IntermediateBuildFilesPath/swift-custom-dump.build/Release-iphoneos/CustomDump.build/Objects-normal/arm64/Swift.o: No such file or directory

**To Reproduce**
Zip up a project that reproduces the behavior and attach it by dragging it here.

I deleted derived data, clean build project, restart PC and did everything I could to try resolving this but it didn't work.

```swift
// And/or enter code that reproduces the behavior here.

```

**Expected behavior**
Give a clear and concise description of what you expected to happen.

**Screenshots**

**Environment**
  - swift-custom-dump version [e.g. 0.3.0] -> 0.11.1
  - Xcode [e.g. 13.2.1] -> 15.3
  - Swift [e.g. 5.5.2] -> 
  - OS: [e.g. iOS 15.2] -> 14.3.1 (23D60)

**Additional context**
Add any more context about the problem here.

**Comment by RuiAAPeres** [comment]
I am seeing the same issue.

**Comment by mbrandonw** [comment]
Hi @filip-aetherius and @RuiAAPeres, this was fixed in 1.2.1. Please update your dependence on swift-custom-dump.

**Comment by peter-alt-eb** [comment]
@mbrandonw could this fix get added to the older version as well?
I asked here https://github.com/pointfreeco/swift-custom-dump/issues/107#issuecomment-1989538713 because some projects are still stuck on Pre-1.0 TCA.

**Comment by stephencelis** [comment]
This fix has been back-ported to the 0.x series: https://github.com/pointfreeco/swift-custom-dump/releases/tag/0.11.2
