### ISSUE TITLE
Xcode 13.2 Compile Error

### ISSUE THREAD

**Issue by romero-ios** [pointfreeco/swift-custom-dump#32]
I have a project that depends on `swift-composable-architecture` which depends on this package. I am using the latest release, v0.30.0.
After updating to Xcode 13.2 and doing a clean build, my project fails to compile.

Please refer to the screenshots for the issue I am seeing.

<img width="1433" alt="Screen Shot 2021-12-14 at 12 48 49 AM" src="https://user-images.githubusercontent.com/8164778/145940812-cfdea17b-2a10-4bd3-b854-642e3a048b50.png">
<img width="277" alt="Screen Shot 2021-12-14 at 12 48 54 AM" src="https://user-images.githubusercontent.com/8164778/145940816-187cc352-edd0-44bc-a74b-1a1fd8472e50.png">

The `Package.swift` for my project declares:
```
 platforms: [
    .iOS(.v15)
  ],
```
So I do not understand why I am encountering this issue.

**Comment by stephencelis** [comment]
Hi @romero-ios! Are you on the latest version? I believe this is a bug in the new build system that we merged a workaround for: #30.

**Comment by subdan** [comment]
I have the same issue on a release version.

**Comment by romero-ios** [comment]
Updated to the latest package worked! Thanks @stephencelis
