### ISSUE TITLE
Version 0.4.0 does not compile

### ISSUE THREAD

**Issue by chernousov-m** [pointfreeco/swift-custom-dump#40]
CoreImage extensions with availability constraints result in the following error

`Protocol 'CustomDumpStringConvertible' requires 'customDumpDescription' to be available in iOS 9.0.0 and newer`

**Comment by chernousov-m** [comment]
You pulled the release, but SPM uses git tags as version markers
I'll share the environment info in a few minutes

**Comment by stephencelis** [comment]
@chernousov-m Right, you need to clear your SPM cache or lock to 0.3.0 to resolve. Sorry for the churn. The release was only out for a brief moment and we pulled it to minimize damage, but it looks like you were one of the few that pulled things in that window.

**Comment by chernousov-m** [comment]
@stephencelis But isn't there still a tag 0.4.0? How can we lock to 0.3.0 if it's not our dependency, but The Composable Architecture itself uses swift-custom-dump

**Comment by kamcma** [comment]
I am also experiencing this issue. M1 Air, macOS 12.2.1, Xcode 13.2.1, iOS target, 15.0. I am opted in to the new Swift build system.

```zsh
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/SwiftUI.swift:5:13: error: cannot find type 'Animation' in scope
  extension Animation: CustomDumpStringConvertible {
            ^~~~~~~~~
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/SwiftUI.swift:37:13: error: cannot find type 'LocalizedStringKey' in scope
  extension LocalizedStringKey: CustomDumpRepresentable {
            ^~~~~~~~~~~~~~~~~~
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:77:28: error: 'announcement' is only available in iOS 13.0 or newer
          allCases.append(.announcement)
                           ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:77:28: note: add 'if #available' version check
          allCases.append(.announcement)
                           ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:24:16: note: add @available attribute to enclosing property
    public var customDumpMirror: Mirror {
               ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:84:12: error: 'criticalAlert' is only available in iOS 12.0 or newer
          .criticalAlert,
           ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:84:12: note: add 'if #available' version check
          .criticalAlert,
           ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:24:16: note: add @available attribute to enclosing property
    public var customDumpMirror: Mirror {
               ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:85:12: error: 'providesAppNotificationSettings' is only available in iOS 12.0 or newer
          .providesAppNotificationSettings,
           ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:85:12: note: add 'if #available' version check
          .providesAppNotificationSettings,
           ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:24:16: note: add @available attribute to enclosing property
    public var customDumpMirror: Mirror {
               ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:86:12: error: 'provisional' is only available in iOS 12.0 or newer
          .provisional,
           ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:86:12: note: add 'if #available' version check
          .provisional,
           ^
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/UserNotifications.swift:24:16: note: add @available attribute to enclosing property
    public var customDumpMirror: Mirror {
               ^

SwiftDriverJob-Emit-Module normal arm64 Emitting\ module\ for\ CustomDump (in target 'CustomDump' from project 'swift-custom-dump')
    cd /Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump
```

If I pin to main, it shrinks to:

```zsh
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/SwiftUI.swift:5:13: error: cannot find type 'Animation' in scope
  extension Animation: CustomDumpStringConvertible {
            ^~~~~~~~~
/Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/SwiftUI.swift:37:13: error: cannot find type 'LocalizedStringKey' in scope
  extension LocalizedStringKey: CustomDumpRepresentable {
```

@chernousov-m, I have found that explicitly pinning to swift-custom-dump to 0.3.0 is a workaround for the short-term. That's all swift-composable-architecture requires. Just add it as a dependency, don't add it to any targets, Xcode will use it as a constraint when trying to pick version numbers.

**Comment by chernousov-m** [comment]
@stephencelis No, we use Xcode 12.5

**Comment by kamcma** [comment]
Still get these couple errors on `main` at the moment:

> If I pin to main, it shrinks to:
> 
> ```shell
> /Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/SwiftUI.swift:5:13: error: cannot find type 'Animation' in scope
>   extension Animation: CustomDumpStringConvertible {
>             ^~~~~~~~~
> /Users/kylemcmahon/Library/Developer/Xcode/DerivedData/Guetzlidose-dxrqljmoguvgrtcidlcoutzmklno/SourcePackages/checkouts/swift-custom-dump/Sources/CustomDump/Conformances/SwiftUI.swift:37:13: error: cannot find type 'LocalizedStringKey' in scope
>   extension LocalizedStringKey: CustomDumpRepresentable {
> ```

(Speaking only for myself, I am not critically blocked by this at the moment, so no rush from me.)

**Comment by stephencelis** [comment]
@chernousov-m Out of curiosity, is there something preventing you from upgrading? Xcode's had 4 non-beta releases since 12.5, and 12.5 contains a version of Swift with some significant bugs around extending types with protocol conformances (which is what this library does). 12.5 is also unsupported on Apple's latest OS.

Ideally we'd like to support Xcode 12.5, but we may need a little help to get there if you are stuck on that release.

**Comment by chernousov-m** [comment]
@stephencelis 
macOS Big Sur 11.5.1
Xcode 12.5
iPhone 8 iOS 14.5

tuist prevented us from upgrading, but now it works with 13 Xcode and we're going to migrate ASAP

**Comment by kamcma** [comment]
Again speaking only for myself, I'm able to pin to 0.3.0 for the time being, so no rush to revert from me if you want to keep investigating. Just trying to contribute some data points. 👍 (Love PF, thanks for everything!)

**Comment by stephencelis** [comment]
@kamcma On further investigation we are going to back out of loosening the platform requirements, so 0.3.0 will remain the latest release. It'd be nice to remove them but doesn't appear possible without incurring issues with Apple's frameworks.

@chernousov-m Were you able to fix things? You may need to do something as simple as remove/re-add TCA to your downstream project to give things a kick and pick up 0.3.0 again.

**Comment by chernousov-m** [comment]
@stephencelis Yeah, our CI machines load packages on every build, so everything got fixed as soon as you removed the tag
@mamouneyya Thank you, I'll remember that in case I need it again :)

**Comment by stephencelis** [comment]
@chernousov-m Going to close this out for now since 0.4.0 won't be released in the form it took that broke things 😄 Thanks for reporting!
